# For local development
services:
  dito:
    build:
      context: .
      dockerfile: packages/dito/Dockerfile
    env_file:
      - packages/dito/.env
    # For local development with docker-compose (not working yet)
    # volumes:
    #   - ./packages/dito:/home/node/src/packages/dito
    #   - /home/node/src/node_modules
    ports:
      - 3000:3000
  tool-finder:
    build:
      context: .
      dockerfile: packages/tool-finder/Dockerfile
    ports:
      - 8080:8080
