export const PATH_INFO: string = "/";
export const PATH_QUIZ: string = "/werkzeugfinder";
export const PATH_RESULT: string = PATH_QUIZ + "/empfehlung";
export const PATH_FLOWCHART: string = "/flussdiagramm"; // Must match with the ID of the cluster in data.json
export const PATH_DECISIONTREE: string = "/entscheidungsbaum"; // Must match with the ID of the cluster in data.json
export const PATH_DIAGRAM: string = "/schaubild"; // Must match with the ID of the cluster in data.json
export const PATH_IMPRINT: string = "/impressum";
export const PATH_PRIVACY: string = "/datenschutz";
// export const PATH_COOKIE: string = "/cookie-einstellungen";
export const PATH_A11Y: string = "/barrierefreiheit";
// export const PATH_OSS: string = "/open-source-code";
