name: PipelineShared

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  # Allow to run this workflow manually
  workflow_dispatch:

jobs:
  changes:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    outputs:
      packages: ${{ steps.filter.outputs.changes }}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            dito:
              - "**"
              - "!packages/**"
              - "packages/shared/**"
              - "packages/dito/**"
              - "!.github/workflows/pipeline-*"
              - ".github/workflows/pipeline-shared.yml"
              - ".github/workflows/pipeline-dito.yml"
            tool-finder:
              - "**"
              - "!packages/**"
              - "packages/shared/**"
              - "packages/tool-finder/**"
              - "!.github/workflows/pipeline-*"
              - ".github/workflows/pipeline-shared.yml"
              - ".github/workflows/pipeline-tool-finder.yml"

  check-and-test:
    uses: ./.github/workflows/check-and-test.yml
    secrets: inherit

  vulnerability-scan:
    uses: ./.github/workflows/scan.yml
    secrets: inherit

  build-and-deploy:
    needs:
      - changes
      - check-and-test
      - vulnerability-scan
    if: ${{ github.ref == 'refs/heads/main' }}
    uses: ./.github/workflows/build-and-deploy.yml
    strategy:
      fail-fast: false
      max-parallel: 2
      matrix:
        package: ${{ fromJSON(needs.changes.outputs.packages) }}
    with:
      package: ${{ matrix.package }}
      environment: production
    secrets: inherit
