name: Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  # Allow to run this workflow manually
  workflow_dispatch:

jobs:
  changes:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    outputs:
      packages: ${{ steps.filter.outputs.changes }} # Contains the list of packages that have changed
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            dito:
              - "**"
              - "!packages/**"
              - "packages/shared/**"
              - "packages/dito/**"
            tool-finder:
              - "**"
              - "!packages/**"
              - "packages/shared/**"
              - "packages/tool-finder/**"

  check-and-test:
    uses: ./.github/workflows/check-and-test.yml
    secrets: inherit

  vulnerability-scan:
    uses: ./.github/workflows/scan.yml
    secrets: inherit

  build-and-deploy:
    needs:
      - changes
      - check-and-test
      - vulnerability-scan
    if: ${{ github.ref == 'refs/heads/main' }}
    strategy:
      fail-fast: false
      max-parallel: 2
      matrix:
        package: ${{ fromJSON(needs.changes.outputs.packages) }}
    uses: ./.github/workflows/build-and-deploy.yml
    with:
      package: ${{ matrix.package }}
      environment: production
    secrets: inherit
