name: PipelineShared

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - "**"
      - "!packages/**"
      - "packages/shared/**"
      - "!.github/workflows/pipeline-*"
      - ".github/workflows/pipeline-shared.yml"
  pull_request:
    branches: [main]
    paths:
      - "**"
      - "!packages/**"
      - "packages/shared/**"
      - "!.github/workflows/pipeline-*"
      - ".github/workflows/pipeline-shared.yml"

jobs:
  check-and-test:
    uses: ./.github/workflows/check-and-test.yml
    secrets: inherit

  vulnerability-scan:
    uses: ./.github/workflows/scan.yml
    secrets: inherit

  build-and-deploy:
    needs:
      - check-and-test
      - vulnerability-scan
    if: ${{ github.ref == 'refs/heads/main' }}
    uses: ./.github/workflows/build-and-deploy.yml
    strategy:
      fail-fast: false
      matrix:
        package: [dito, tool-finder]
    with:
      package: ${{ matrix.package }}
      environment: production
    secrets: inherit
